source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SWActivityIndicatorView Example' do
  pod "SWActivityIndicatorView", :path => "../"
  
  target 'SWActivityIndicatorView Example_Tests' do
      inherit! :search_paths
  end
end
